"use client";

import { useState } from "react";

type ScenarioOption = {
  id: string;
  text: string;
};

type Scenario = {
  id: number;
  title: string;
  prompt: string;
  question: string;
  options: ScenarioOption[];
  correctAnswer: string;
  correctFeedback: string;
  incorrectFeedback: string;
};

const scenarios: Scenario[] = [
  {
    id: 1,
    title: "Scenario 1: Compliance Training",
    prompt:
      "You are designing a compliance training module for healthcare employees. You use AI to generate the content and publish it without reviewing it.",
    question: "What is the biggest issue with this approach?",
    options: [
      { id: "A", text: "AI is too slow for compliance training" },
      {
        id: "B",
        text: "AI-generated content may be inaccurate or biased",
      },
      { id: "C", text: "AI cannot generate text effectively" },
      { id: "D", text: "There is no issue — this is efficient" },
    ],
    correctAnswer: "B",
    correctFeedback:
      "Correct. AI can accelerate content creation, but compliance training requires accuracy, legal alignment, and subject matter validation. AI outputs must always be reviewed before deployment.",
    incorrectFeedback:
      "Not quite. The key issue is that AI-generated content may be inaccurate or biased. In high-risk environments like compliance, human validation is essential.",
  },
  {
    id: 2,
    title: "Scenario 2: Scenario Writing Support",
    prompt:
      "You are building a sales training course and use AI to draft three customer objection scenarios. You review them, edit them for realism, and align them to your audience before publishing.",
    question: "What best describes this use of AI?",
    options: [
      {
        id: "A",
        text: "Irresponsible, because AI should never help write training",
      },
      {
        id: "B",
        text: "A strong use of AI with human oversight and design judgment",
      },
      {
        id: "C",
        text: "Unnecessary, because instructional designers should do everything manually",
      },
      {
        id: "D",
        text: "Risky only because scenarios cannot be generated by AI",
      },
    ],
    correctAnswer: "B",
    correctFeedback:
      "Correct. This is a good example of AI as an accelerator, not a replacement. The designer still applies judgment, audience alignment, and quality control.",
    incorrectFeedback:
      "Not quite. This scenario reflects responsible AI use because the designer reviews, edits, and validates the output before using it.",
  },
  {
    id: 3,
    title: "Scenario 3: Learner Trust",
    prompt:
      "A learning team adds an AI coach to a leadership program, but never tells learners that the feedback is AI-generated.",
    question: "What is the strongest concern in this situation?",
    options: [
      { id: "A", text: "The interface will probably load too slowly" },
      {
        id: "B",
        text: "Learners may lose trust if the use of AI is not transparent",
      },
      { id: "C", text: "AI can only be used in technical training" },
      {
        id: "D",
        text: "Leadership content should never include digital tools",
      },
    ],
    correctAnswer: "B",
    correctFeedback:
      "Correct. Transparency matters. If learners do not know when AI is involved, trust can erode, especially when the system is offering evaluative or coaching feedback.",
    incorrectFeedback:
      "Not quite. The strongest issue here is learner trust and transparency. Responsible AI use includes being clear about where and how AI is being used.",
  },
];

export default function AIReflection() {
  const [currentScenarioIndex, setCurrentScenarioIndex] = useState(0);
  const [selected, setSelected] = useState<string | null>(null);
  const [showFeedback, setShowFeedback] = useState(false);
  const [score, setScore] = useState(0);
  const [showSummary, setShowSummary] = useState(false);

  const currentScenario = scenarios[currentScenarioIndex];
  const isCorrect = selected === currentScenario.correctAnswer;
  const isLastScenario = currentScenarioIndex === scenarios.length - 1;

  function handleSelect(id: string) {
    setSelected(id);
    setShowFeedback(true);

    if (id === currentScenario.correctAnswer) {
      setScore((prev) => prev + 1);
    }
  }

  function handleNextScenario() {
    if (isLastScenario) {
      setShowSummary(true);
      return;
    }

    setCurrentScenarioIndex((prev) => prev + 1);
    setSelected(null);
    setShowFeedback(false);
  }

  function handleRestart() {
    setCurrentScenarioIndex(0);
    setSelected(null);
    setShowFeedback(false);
    setScore(0);
    setShowSummary(false);
  }

  function getScoreMessage() {
    if (score === scenarios.length) {
      return "Excellent judgment. You’re demonstrating a strong understanding of where AI can help and where human oversight is essential.";
    }

    if (score === 2) {
      return "Strong work. You’re building good instincts around responsible AI use in learning design.";
    }

    if (score === 1) {
      return "You’re on the right track, but there are still some important distinctions to strengthen in your AI decision-making.";
    }

    return "This is a good reminder that AI literacy is not just about using tools — it’s about making sound design judgments. Try the scenarios again.";
  }

  if (showSummary) {
    return (
      <div className="border border-blue-500 rounded-xl p-6 space-y-6">
        <h3 className="text-2xl font-semibold">AI Judgment Practice Summary</h3>

        <p className="text-white text-lg font-medium">
          Your Score: {score} / {scenarios.length}
        </p>

        <p className="text-gray-400 leading-relaxed">{getScoreMessage()}</p>

        <button
          type="button"
          onClick={handleRestart}
          className="rounded-lg bg-white text-black px-5 py-3 font-medium hover:bg-gray-200 transition">
          Restart Practice
        </button>
      </div>
    );
  }

  return (
    <div className="border border-blue-500 rounded-xl p-6 space-y-6">
      <div className="flex items-center justify-between gap-4">
        <h3 className="text-2xl font-semibold">AI Judgment Practice</h3>

        <p className="text-sm text-gray-400">
          Scenario {currentScenarioIndex + 1} of {scenarios.length}
        </p>
      </div>

      <div>
        <h4 className="text-lg font-medium mb-2">{currentScenario.title}</h4>

        <p className="text-gray-400 leading-relaxed">
          {currentScenario.prompt}
        </p>
      </div>

      <p className="text-white font-medium">{currentScenario.question}</p>

      <div className="space-y-3">
        {currentScenario.options.map((option) => (
          <button
            key={option.id}
            onClick={() => handleSelect(option.id)}
            disabled={showFeedback}
            className={`w-full text-left p-3 rounded-lg border transition ${
              selected === option.id
                ? "bg-blue-600 border-blue-400"
                : "border-gray-600 hover:bg-gray-800"
            } ${showFeedback ? "cursor-default" : ""}`}>
            {option.id}. {option.text}
          </button>
        ))}
      </div>

      {showFeedback && (
        <div className="mt-4 p-4 rounded-lg bg-gray-800 space-y-4">
          <p className={isCorrect ? "text-green-400" : "text-red-400"}>
            {isCorrect
              ? currentScenario.correctFeedback
              : currentScenario.incorrectFeedback}
          </p>

          <button
            type="button"
            onClick={handleNextScenario}
            className="rounded-lg bg-white text-black px-5 py-3 font-medium hover:bg-gray-200 transition">
            {isLastScenario ? "View Summary →" : "Next Scenario →"}
          </button>
        </div>
      )}
    </div>
  );
}
